### ISSUE TITLE
Deserialize dates to `DateTime<Utc>`

### ISSUE THREAD

**Issue by ifiokjr** [panghu-huang/octocrate#24]
### Description

Currently, dates are deserialized as `String` when it would be more convenient for some libraries to deserialize them as `DateTime<Utc>`.

Since the `chrono` library is already a dependency of the `octocrate-core` library, there is no need to hide it behind a feature flag.

**Comment by ifiokjr** [comment]
@panghu-huang do you know a quick way of implementing this?

**Comment by panghu-huang** [comment]
Yes, the `format` field is present in the schema but is currently being ignored and not processed. If you need to deserialize it into `DateTime<Utc>`, then we'll need to handle the `format` information.

**Comment by panghu-huang** [comment]
Hi @ifiokjr 

After careful consideration, I am inclined to retain the original data structure of the GitHub API, and I do not require the deserialization of time into `DateTime<Utc>`.
