### ISSUE TITLE
Repo does not reflect the published version on crates.io

### ISSUE THREAD

**Issue by ifiokjr** [panghu-huang/octocrate#3]
The current version of this repo is a few months behind the currently published version on crates.io. Is it possible to resolve this?

Also, if possible, I'd like to contribute to this library as I will be using it extensively over the next few months.

**Comment by panghu-huang** [comment]
Hi @ifiokjr 

Thank you for your interest in octocrate. I have updated the entire architecture today, and now the API is generated from https://github.com/github/rest-api-description (I have already used the new v3 version in production projects). You can check out the new README at https://github.com/panghu-huang/octocrate for more information.

I have moved the old version to https://github.com/panghu-huang/octocrate/tree/v1. Contributions to the code or feedback are always welcome

**Comment by ifiokjr** [comment]
Amazing!
