### ISSUE TITLE
InstallationToken doesn't implement ExpirableToken trait

### ISSUE THREAD

**Issue by dawnchan030920** [panghu-huang/octocrate#42]

**Comment by panghu-huang** [comment]
Hi @dawnchan030920 

This issue has been fixed in [octocrate@2.0.0](https://crates.io/crates/octocrate/2.0.0)

**Comment by dawnchan030920** [comment]
Thank you for your quick response

**Comment by ifiokjr** [comment]
@panghu-huang the reason for the trait was that it was important to avoid importing `octocrate-core` into `octocrate-types`. 

This breaks all wasm builds relying on `octocrate-types`. 

Can't the user just import the `ExpirableToken` trait?

If this is difficult, we can export a `prelude` which includes this trait.

**Comment by panghu-huang** [comment]
> @panghu-huang the reason for the trait was that it was important to avoid importing `octocrate-core` into `octocrate-types`.
> 
> This breaks all wasm builds relying on `octocrate-types`.
> 
> Can't the user just import the `ExpirableToken` trait?
> 
> If this is difficult, we can export a `prelude` which includes this trait.

Sure, here is the translated text:

---

Although we have verified that the installation token works correctly at https://github.com/panghu-huang/octocrate/blob/main/octocrate/examples/apps.rs#L35, I do encounter an "unimplemented trait" error when importing octocrate into a separate project. I think it’s necessary to implement this trait in the crate where the installation token is defined.

Can you identify which dependency in core is not compatible with wasm? If not, I'll try to fix it using other methods.

**Comment by panghu-huang** [comment]
fixed in 2.0.1
