### ISSUE TITLE
`octocrate-types@2.0.0` breaks client code

### ISSUE THREAD

**Issue by ifiokjr** [panghu-huang/octocrate#47]
### Description

In issue #4 we split off the single crate into multiple crates to support using `octocrate-types` on both the frontend and backend. 

The new version (2.0.0) breaks this since it imports `octocrate-core` which includes several wasm incompatible modules.

As a result, my build breaks after an upgrade.

Would it be possible to make sure that the `octocrate-types` is purely for types and models so that it can be shared in all environments?

**Comment by panghu-huang** [comment]
Please temporarily use this version https://crates.io/crates/octocrate/2.0.0-beta.1 as a workaround.

**Comment by panghu-huang** [comment]
fixed in 2.0.1
