### ISSUE TITLE
no field `pulls` on type `GitHubAPI`

### ISSUE THREAD

**Issue by grnmeira** [panghu-huang/octocrate#50]
I was trying to run the first example from the README, and faced this issue. It's like `pulls` is not available in `GitHubAPI`. Couldn't find it in the docs either, and even trying to add the feature `pulls`, I get a complaint from cargo saying it doesn't exist.

**Comment by panghu-huang** [comment]
Hi, could you provide more information or a repository to reproduce this issue? I've already tested it, and the problem does not occur (with the `pulls` feature enabled).

**Comment by grnmeira** [comment]
Let me know if this helps. This is my Cargo.toml:

```
[package]
name = "envoy-github-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
octocrate = "*"
octocrate-types = { version = "*", features = ["repos", "git", "pulls", "issues", "users", "search"] }
tokio = { version = "1.41.1", features = ["full"] }
```

And this is my main.rs:

```
use octocrate::{APIConfig, Error, GitHubAPI};

#[tokio::main]
async fn main() {
  let config = APIConfig::default().shared();

  let api = GitHubAPI::new(&config);

  let pull_request = api
    .pulls
    .get("panghu-huang", "octocrate", 1)
    .send()
    .await
    .unwrap();
}
```

**Comment by panghu-huang** [comment]
Simply keep `octocrate` and enable the corresponding features for it:

```diff
[package]
name = "envoy-github-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
+ octocrate = { version = "*", features = ["repos", "git", "pulls", "issues", "users", "search"] }
- octocrate = "*"
- octocrate-types = { version = "*", features = ["repos", "git", "pulls", "issues", "users", "search"] }
tokio = { version = "1.41.1", features = ["full"] }
```

You can remove `octocrate-types` since everything has already been re-exported in `octocrate`:  
https://github.com/panghu-huang/octocrate/blob/main/octocrate/src/lib.rs#L6  

```rust
pub use octocrate_types::*;
```

**Comment by grnmeira** [comment]
Thanks @panghu-huang, that worked out great. I probably made a mistake copying and pasting things from the README instructions 🙃
