### ISSUE TITLE
Wrap data in a `GitHubResponse` struct

### ISSUE THREAD

**Issue by ifiokjr** [panghu-huang/octocrate#6]
### Description

Presently, when `Request::send(self)` is called, it just returns the data. 

Let's wrap the data in a `GitHubResponse` struct for access to some of the metadata around the request.

```rust
#[derive(Clone)]
pub struct GithubResponse<Data> {
	pub data: Data,
	pub headers: HeaderMap,
	pub status: StatusCode,
	pub version: Version,
	pub content_length: Option<u64>,
	pub url: Url,
}
```

This would be a breaking change.

**Comment by panghu-huang** [comment]
The `GitHubResponse` is a good idea. However, it's worth noting that in the first version, for convenience, I only parse the `application/json` response type and temporarily ignore the others.
