### ISSUE TITLE
Switch from `derive_builder` to `typed-builder`

### ISSUE THREAD

**Issue by ifiokjr** [panghu-huang/octocrate#7]
### Description

All the model and webhook structs are using the `derived_builder` macro for a builder that implements runtime builder checks. 

Have you considered using [typed-builder](https://idanarye.github.io/rust-typed-builder/typed_builder/derive.TypedBuilder.html) which implements compile time checks without the need for an `unwrap()` or runtime checking of the created structs.

I can create a pull request if it would be of interest to you?

**Comment by panghu-huang** [comment]
I've looked into `typed_builder`, and I find its usage more elegant than `derived_builder`.

**Comment by ifiokjr** [comment]
I'm creating a PR for this now.
